_wandb:
    value:
        cli_version: 0.26.1
        e:
            28id7l5l1f7lylkof27lxz3q92sge9wf:
                args:
                    - --save_dir
                    - ./out
                    - --save_weight
                    - pretrain
                    - --save_interval
                    - "1000"
                    - --epochs
                    - "2"
                    - --batch_size
                    - "32"
                    - --learning_rate
                    - "5e-4"
                    - --accumulation_steps
                    - "8"
                    - --grad_clip
                    - "1.0"
                    - --device
                    - cuda:0
                    - --dtype
                    - bfloat16
                    - --num_workers
                    - "8"
                    - --use_compile
                    - "1"
                    - --hidden_size
                    - "768"
                    - --num_hidden_layers
                    - "8"
                    - --max_seq_len
                    - "340"
                    - --use_moe
                    - "1"
                    - --data_path
                    - ../dataset/pretrain_t2t_mini.jsonl
                    - --from_weight
                    - none
                    - --from_resume
                    - "0"
                    - --log_interval
                    - "100"
                    - --wandb_project
                    - MiniMind-Pretrain
                    - --use_wandb
                codePath: trainer/train_pretrain.py
                codePathLocal: train_pretrain.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1770442534912"
                        used: "410932436992"
                email: 3134543919@qq.com
                executable: /usr/bin/python3
                git:
                    commit: f1567f13d06abc4d71f6d37d792cd1f0a99d38e1
                    remote: https://github.com/Littleprince456/self_minimind.git
                gpu: NVIDIA A30
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "25769803776"
                      name: NVIDIA A30
                      uuid: GPU-40ab53eb-5087-1083-0c2c-b5104ed32f6b
                host: dc03-pb-t263-n014
                memory:
                    total: "1081537007616"
                os: Linux-5.4.250.bsk.9-amd64-x86_64-with-glibc2.36
                program: /workspace/self_minimind/trainer/train_pretrain.py
                python: CPython 3.11.2
                root: /workspace/self_minimind/trainer
                startedAt: "2026-05-28T06:09:26.164131Z"
                writerId: 28id7l5l1f7lylkof27lxz3q92sge9wf
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
            "3":
                - 13
            "4": 3.11.2
            "5": 0.26.1
            "6": 4.57.6
            "12": 0.26.1
            "13": linux-x86_64
